### ISSUE TITLE
选择图片的时候闪退，拍照都OK。卸载了二维码插件还是不行~

### ISSUE THREAD

**Issue by justdoitgo** [giantss/cordova-plugin-ImagePicker#33]
选择图片的时候闪退，拍照都OK。卸载了二维码插件还是不行~

**Comment by justdoitgo** [comment]
01-22 15:01:55.074 18126-18126/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.baoyehb.qcsg, PID: 18126
                                                   java.lang.NullPointerException
                                                       at com.giants.imagepicker.adapter.ImageRecyclerAdapter$ImageViewHolder.bind(ImageRecyclerAdapter.java:176)
                                                       at com.giants.imagepicker.adapter.ImageRecyclerAdapter.onBindViewHolder(ImageRecyclerAdapter.java:95)
                                                       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6308)
                                                       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6341)

**Comment by giantss** [comment]
机型  android版本 环境发现来看看

**Comment by TyroneLao** [comment]
我用华为p7，android5.1，也出现了闪退

**Comment by justdoitgo** [comment]
我的解决了，最终还是和com.android.support:support-v4: 这个有关系，部分插件卸载后或者改了依赖还是出问题。（只要装了就冲突，闪退）。

**Comment by TyroneLao** [comment]
com.android.support:support-v4 是在哪里的呢？android根目录下的build.gradle吗？

**Comment by lovelyelfpop** [comment]
https://github.com/dpa99c/cordova-android-support-gradle-release
可以用这个插件，统一不同插件要求依赖不同版本的 support 库的问题
