### ISSUE TITLE
cordova build报错

### ISSUE THREAD

**Issue by lulersoft** [giantss/cordova-plugin-ImagePicker#44]
PS D:\cordova_project\telem> cordova build android
(node:11872) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'text' of null
    at updateProjectAccordingTo (D:\cordova_project\telem\platforms\android\cordova\lib\prepare.js:174:51)
    at D:\cordova_project\telem\platforms\android\cordova\lib\prepare.js:47:16
    at _fulfilled (D:\cordova_project\telem\platforms\android\cordova\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (D:\cordova_project\telem\platforms\android\cordova\node_modules\q\q.js:883:30)
    at Promise.promise.promiseDispatch (D:\cordova_project\telem\platforms\android\cordova\node_modules\q\q.js:816:13)
    at D:\cordova_project\telem\platforms\android\cordova\node_modules\q\q.js:570:49
    at runSingle (D:\cordova_project\telem\platforms\android\cordova\node_modules\q\q.js:137:13)
    at flush (D:\cordova_project\telem\platforms\android\cordova\node_modules\q\q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:150:11)
    at Function.Module.runMain (module.js:703:11)
(node:11872) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11872) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by giantss** [comment]
这个错误应该与ImagePicker插件无关，如果有问题可以继续打开 issues讨论
